// PHP/phase3/support-hub-ai/resources/js/Pages/Tickets/Create.vue
<script setup>
import AppLayout from '@/Layouts/AppLayout.vue';
import { useForm } from '@inertiajs/vue3';
import { defineProps } from 'vue';

// The controller is passing a 'departments' prop
const props = defineProps({
    departments: Array,
});

// Inertia's form helper. It wraps our form data and provides methods.
const form = useForm({
    title: '',
    department_id: null,
    content: '',
});

// The function to call when the form is submitted
const submit = () => {
    form.post(route('tickets.store'), {
        onSuccess: () => form.reset(), // Reset form fields on success
    });
};
</script>

<template>
    <AppLayout title="Create Ticket">
        <template #header>
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                Create a New Support Ticket
            </h2>
        </template>

        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                    <div class="p-6 lg:p-8 bg-white border-b border-gray-200">
                        <form @submit.prevent="submit">
                            <!-- Title -->
                            <div>
                                <label for="title" class="block font-medium text-sm text-gray-700">Title</label>
                                <input id="title" v-model="form.title" type="text" class="block w-full mt-1" required>
                                <div v-if="form.errors.title" class="text-sm text-red-600 mt-1">{{ form.errors.title }}</div>
                            </div>

                            <!-- Department -->
                            <div class="mt-4">
                                <label for="department" class="block font-medium text-sm text-gray-700">Department</label>
                                <select id="department" v-model="form.department_id" class="block w-full mt-1" required>
                                    <option :value="null" disabled>Select a department</option>
                                    <option v-for="department in departments" :key="department.id" :value="department.id">
                                        {{ department.name }}
                                    </option>
                                </select>
                                <div v-if="form.errors.department_id" class="text-sm text-red-600 mt-1">{{ form.errors.department_id }}</div>
                            </div>

                            <!-- Content -->
                            <div class="mt-4">
                                <label for="content" class="block font-medium text-sm text-gray-700">Details</label>
                                <textarea id="content" v-model="form.content" rows="5" class="block w-full mt-1" required></textarea>
                                <div v-if="form.errors.content" class="text-sm text-red-600 mt-1">{{ form.errors.content }}</div>
                            </div>

                            <!-- Submit Button -->
                            <div class="flex items-center justify-end mt-4">
                                <button type="submit" :disabled="form.processing" class="px-4 py-2 bg-gray-800 text-white rounded-md">
                                    Create Ticket
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </AppLayout>
</template>

// PHP/phase4/deal-analyser/resources/js/Pages/Deals/Create.jsx
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, useForm } from '@inertiajs/react';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import InputError from '@/Components/InputError';
import { useState, useEffect } from 'react';

export default function Create() {
    const { data, setData, post, processing, errors, reset } = useForm({
        image: null,
    });

    const [imagePreview, setImagePreview] = useState(null);

    useEffect(() => {
        if (data.image) {
            const previewUrl = URL.createObjectURL(data.image);
            setImagePreview(previewUrl);
            return () => URL.revokeObjectURL(previewUrl);
        }
    }, [data.image]);

    const submit = (e) => {
        e.preventDefault();
        post(route('deals.store'), {
            forceFormData: true,
            onSuccess: () => {
                reset();
                setImagePreview(null);
            },
        });
    };

    return (
        <AuthenticatedLayout
            header={<h2 className="text-xl font-semibold leading-tight text-gray-800">Upload Deal Image</h2>}
        >
            <Head title="Upload Deal Image" />

            <div className="py-12">
                <div className="mx-auto max-w-3xl sm:px-6 lg:px-8">
                    <div className="overflow-hidden bg-white shadow-sm sm:rounded-lg">
                        <form onSubmit={submit} className="p-8 space-y-6">
                            <div className="text-sm text-gray-600">
                                Upload a clear image related to the deal. Our AI will extract the key details from the image and populate the deal information for you.
                            </div>

                            <div>
                                <InputLabel htmlFor="image" value="Deal Image" />
                                <input
                                    id="image"
                                    type="file"
                                    className="mt-1 block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100"
                                    accept="image/jpeg,image/jpg,image/png,image/gif,.jpeg,.jpg"
                                    onChange={(e) => setData('image', e.target.files[0])}
                                    required
                                />
                                <InputError message={errors.image} className="mt-2" />
                            </div>
                            
                            {imagePreview && (
                                <div className="mt-4">
                                    <img src={imagePreview} alt="Preview" className="h-48 w-auto rounded-md object-cover" />
                                </div>
                            )}

                            <div className="flex items-center justify-end">
                                <PrimaryButton disabled={processing}>
                                    {processing ? 'Uploading...' : 'Upload Image'}
                                </PrimaryButton>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}
