// PHP/phase4/deal-analyser/resources/js/Pages/Company/Create.jsx
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, useForm } from '@inertiajs/react';
import TextInput from '@/Components/TextInput';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import { useEffect } from 'react';

export default function Create({ errors, company }) {
    const { data, setData, post, put, processing, errors: formErrors, reset } = useForm({
        name: company?.name || '',
        industry: company?.industry || '',
        description: company?.description || '',
        location: company?.location || '',
        size: company?.size || '',
        revenue: company?.revenue || '',
    });

    useEffect(() => {
        return () => {
            reset('password', 'password_confirmation');
        };
    }, []);

    const submit = (e) => {
    e.preventDefault();
    if (company) {
        // The `put` helper will automatically send the form data.
        put(route('company.update', company.id)); // <-- Correct
    } else {
        // The `post` helper will automatically send the form data.
        post(route('company.store')); // <-- Correct
    }
};


    return (
        <AuthenticatedLayout
            header={<h2 className="text-xl font-semibold leading-tight text-gray-800">Company Profile</h2>}
        >
            <Head title="Company Profile" />

            <div className="py-12">
                <div className="mx-auto max-w-3xl sm:px-6 lg:px-8">
                    <div className="overflow-hidden bg-white shadow-sm sm:rounded-lg">
                        <div className="p-6 text-gray-900">
                            <form onSubmit={submit} className="space-y-6">
                                <div>
                                    <InputLabel htmlFor="name">Name</InputLabel>
                                    <TextInput
                                        id="name"
                                        value={data.name}
                                        onChange={(e) => setData('name', e.target.value)}
                                        required
                                    />
                                    {formErrors.name && <p className="mt-2 text-sm text-red-600">{formErrors.name}</p>}
                                </div>

                                <div>
                                    <InputLabel htmlFor="industry">Industry</InputLabel>
                                    <TextInput
                                        id="industry"
                                        value={data.industry}
                                        onChange={(e) => setData('industry', e.target.value)}
                                    />
                                    {formErrors.industry && <p className="mt-2 text-sm text-red-600">{formErrors.industry}</p>}
                                </div>

                                <div>
                                    <InputLabel htmlFor="description">Description</InputLabel>
                                    <textarea
                                        id="description"
                                        value={data.description}
                                        onChange={(e) => setData('description', e.target.value)}
                                        className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                    />
                                    {formErrors.description && <p className="mt-2 text-sm text-red-600">{formErrors.description}</p>}
                                </div>

                                <div className="grid grid-cols-2 gap-4">
                                    <div>
                                        <InputLabel htmlFor="location">Location</InputLabel>
                                        <TextInput
                                            id="location"
                                            value={data.location}
                                            onChange={(e) => setData('location', e.target.value)}
                                        />
                                        {formErrors.location && <p className="mt-2 text-sm text-red-600">{formErrors.location}</p>}
                                    </div>

                                    <div>
                                        <InputLabel htmlFor="size">Size</InputLabel>
                                        <TextInput
                                            id="size"
                                            type="number"
                                            value={data.size}
                                            onChange={(e) => setData('size', e.target.value)}
                                        />
                                        {formErrors.size && <p className="mt-2 text-sm text-red-600">{formErrors.size}</p>}
                                    </div>
                                </div>

                                <div>
                                    <InputLabel htmlFor="revenue">Revenue</InputLabel>
                                    <TextInput
                                        id="revenue"
                                        type="number"
                                        step="0.01"
                                        value={data.revenue}
                                        onChange={(e) => setData('revenue', e.target.value)}
                                    />
                                    {formErrors.revenue && <p className="mt-2 text-sm text-red-600">{formErrors.revenue}</p>}
                                </div>

                                <div className="flex items-center justify-end gap-4">
                                    <PrimaryButton disabled={processing}>{company ? 'Update' : 'Create'}</PrimaryButton>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}

// PHP/phase3/support-hub-ai/resources/js/Pages/Tickets/Create.vue
<script setup>
import AppLayout from '@/Layouts/AppLayout.vue';
import { useForm } from '@inertiajs/vue3';
import { defineProps } from 'vue';

// The controller is passing a 'departments' prop
const props = defineProps({
    departments: Array,
});

// Inertia's form helper. It wraps our form data and provides methods.
const form = useForm({
    title: '',
    department_id: null,
    content: '',
});

// The function to call when the form is submitted
const submit = () => {
    form.post(route('tickets.store'), {
        onSuccess: () => form.reset(), // Reset form fields on success
    });
};
</script>

<template>
    <AppLayout title="Create Ticket">
        <template #header>
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                Create a New Support Ticket
            </h2>
        </template>

        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                    <div class="p-6 lg:p-8 bg-white border-b border-gray-200">
                        <form @submit.prevent="submit">
                            <!-- Title -->
                            <div>
                                <label for="title" class="block font-medium text-sm text-gray-700">Title</label>
                                <input id="title" v-model="form.title" type="text" class="block w-full mt-1" required>
                                <div v-if="form.errors.title" class="text-sm text-red-600 mt-1">{{ form.errors.title }}</div>
                            </div>

                            <!-- Department -->
                            <div class="mt-4">
                                <label for="department" class="block font-medium text-sm text-gray-700">Department</label>
                                <select id="department" v-model="form.department_id" class="block w-full mt-1" required>
                                    <option :value="null" disabled>Select a department</option>
                                    <option v-for="department in departments" :key="department.id" :value="department.id">
                                        {{ department.name }}
                                    </option>
                                </select>
                                <div v-if="form.errors.department_id" class="text-sm text-red-600 mt-1">{{ form.errors.department_id }}</div>
                            </div>

                            <!-- Content -->
                            <div class="mt-4">
                                <label for="content" class="block font-medium text-sm text-gray-700">Details</label>
                                <textarea id="content" v-model="form.content" rows="5" class="block w-full mt-1" required></textarea>
                                <div v-if="form.errors.content" class="text-sm text-red-600 mt-1">{{ form.errors.content }}</div>
                            </div>

                            <!-- Submit Button -->
                            <div class="flex items-center justify-end mt-4">
                                <button type="submit" :disabled="form.processing" class="px-4 py-2 bg-gray-800 text-white rounded-md">
                                    Create Ticket
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </AppLayout>
</template>
