// PHP/phase4/deal-analyser/resources/js/Pages/Company/Show.jsx
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link } from '@inertiajs/react';
import { BuildingOffice2Icon, BriefcaseIcon, MapPinIcon, UsersIcon, BanknotesIcon, PencilSquareIcon, ArrowLeftIcon } from '@heroicons/react/24/outline';

// A reusable component for displaying individual stats
const StatCard = ({ icon, label, value }) => (
    <div className="flex items-start p-4 bg-gray-50 rounded-lg">
        <div className="flex-shrink-0 mr-4">
            {icon}
        </div>
        <div>
            <div className="text-sm font-medium text-gray-500">{label}</div>
            <div className="text-lg font-semibold text-gray-900">{value || 'Not Provided'}</div>
        </div>
    </div>
);

export default function Show({ company }) {
    return (
        <AuthenticatedLayout
            header={
                <div className="flex items-center justify-between">
                    <h2 className="text-xl font-semibold leading-tight text-gray-800">
                        Company Profile
                    </h2>
                    <Link
                        href={route('dashboard')}
                        className="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50"
                    >
                        <ArrowLeftIcon className="w-5 h-5 mr-2 -ml-1" />
                        Back to Dashboard
                    </Link>
                </div>
            }
        >
            <Head title="Company Profile" />

            <div className="py-12">
                <div className="mx-auto max-w-4xl sm:px-6 lg:px-8">
                    <div className="overflow-hidden bg-white shadow-sm sm:rounded-lg">
                        {/* Header Section */}
                        <div className="p-8 border-b border-gray-200">
                            <div className="flex items-center">
                                <div className="flex-shrink-0 w-16 h-16 bg-indigo-100 rounded-full flex items-center justify-center">
                                    <BuildingOffice2Icon className="w-8 h-8 text-indigo-600" />
                                </div>
                                <div className="ml-6">
                                    <h3 className="text-3xl font-bold text-gray-900">{company.name}</h3>
                                    <p className="mt-1 text-lg text-indigo-600 flex items-center">
                                        <BriefcaseIcon className="w-5 h-5 mr-2" />
                                        {company.industry || 'No industry specified'}
                                    </p>
                                </div>
                            </div>
                        </div>

                        {/* Main Content Section */}
                        <div className="p-8">
                            {/* Description */}
                            <div>
                                <h4 className="text-lg font-semibold text-gray-800">About the Company</h4>
                                <p className="mt-2 text-base text-gray-600 leading-relaxed">
                                    {company.description || 'No description provided.'}
                                </p>
                            </div>

                            {/* Stats Grid */}
                            <div className="mt-8">
                                <h4 className="text-lg font-semibold text-gray-800 mb-4">Company Details</h4>
                                <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
                                    <StatCard
                                        icon={<MapPinIcon className="w-8 h-8 text-gray-400" />}
                                        label="Location"
                                        value={company.location}
                                    />
                                    <StatCard
                                        icon={<UsersIcon className="w-8 h-8 text-gray-400" />}
                                        label="Company Size"
                                        value={company.size ? `${company.size.toLocaleString()} employees` : null}
                                    />
                                    <StatCard
                                        icon={<BanknotesIcon className="w-8 h-8 text-gray-400" />}
                                        label="Annual Revenue"
                                        value={company.revenue ? `$${Number(company.revenue).toLocaleString()}` : null}
                                    />
                                </div>
                            </div>
                        </div>

                        {/* Footer Actions */}
                        <div className="px-8 py-4 bg-gray-50 border-t border-gray-200 flex justify-end">
                            <Link
                                href={route('company.edit', company.id)}
                                className="inline-flex items-center justify-center px-4 py-2 text-sm font-semibold text-white bg-indigo-600 rounded-md shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                            >
                                <PencilSquareIcon className="w-5 h-5 mr-2 -ml-1" />
                                Edit Profile
                            </Link>
                        </div>
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}

// PHP/phase3/support-hub-ai/resources/js/Pages/Tickets/Show.vue
<script setup>
import AppLayout from '@/Layouts/AppLayout.vue';
import { defineProps } from 'vue';

const props = defineProps({
    ticket: Object,
});
</script>

<template>
    <AppLayout :title="`Ticket #${ticket.id}`">
        <template #header>
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                Ticket #{{ ticket.id }}: {{ ticket.title }}
            </h2>
        </template>

        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <!-- Main Ticket Details -->
                <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6 lg:p-8">
                    <div class="border-b pb-4 mb-4">
                        <p class="text-gray-600">
                            <strong>Status:</strong> <span class="capitalize">{{ ticket.status }}</span>
                        </p>
                        <p class="text-gray-600">
                            <strong>Department:</strong> {{ ticket.department.name }}
                        </p>
                        <p class="text-gray-600">
                            <strong>Created by:</strong> {{ ticket.user.name }} on {{ new Date(ticket.created_at).toLocaleString() }}
                        </p>
                    </div>
                    <div class="prose max-w-none">
                        <p>{{ ticket.content }}</p>
                    </div>
                </div>

                <!-- Replies Section -->
                <div class="mt-8">
                    <h3 class="font-semibold text-lg text-gray-800 leading-tight mb-4">
                        Conversation
                    </h3>
                    <div class="space-y-6">
                        <!-- Loop through replies -->
                        <div v-for="reply in ticket.replies" :key="reply.id" class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6">
                            <p class="font-bold">{{ reply.user.name }}</p>
                            <p class="text-xs text-gray-500 mb-2">{{ new Date(reply.created_at).toLocaleString() }}</p>
                            <div class="prose max-w-none">
                                <p>{{ reply.content }}</p>
                            </div>
                        </div>

                        <!-- No replies message -->
                        <div v-if="!ticket.replies.length" class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6">
                            <p>No replies yet.</p>
                        </div>
                    </div>
                </div>

                <!-- Reply Form (we will make this functional later) -->
                <div class="mt-8 bg-white overflow-hidden shadow-xl sm:rounded-lg p-6">
                     <h3 class="font-semibold text-lg text-gray-800 leading-tight mb-4">
                        Add a Reply
                    </h3>
                    <form>
                        <textarea rows="5" class="w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm" placeholder="Type your reply..."></textarea>
                        <div class="flex justify-end mt-4">
                             <button type="submit" class="px-4 py-2 bg-gray-800 text-white rounded-md">
                                Submit Reply
                            </button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </AppLayout>
</template>
