// PHP/phase3/support-hub-ai/resources/js/Pages/Agent/Dashboard.vue

<script setup>
import AppLayout from '@/Layouts/AppLayout.vue';
import { defineProps } from 'vue';
import { Link } from '@inertiajs/vue3';
import StatusBadge from '@/Components/StatusBadge.vue';

const props = defineProps({
    tickets: Object,
});
</script>

<template>
    <AppLayout title="Agent Dashboard">
        <template #header>
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                Agent Dashboard
            </h2>
        </template>

        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                    <div class="p-6 lg:p-8 bg-white border-b border-gray-200">
                        <table class="w-full text-left">
                            <thead class="bg-gray-50 border-b-2 border-gray-200">
                                <tr>
                                    <th class="p-4">ID</th>
                                    <th class="p-4">Title</th>
                                    <th class="p-4">Organization</th>
                                    <th class="p-4">User</th>
                                    <th class="p-4">Status</th>
                                    <th class="p-4">Created On</th>
                                </tr>
                            </thead>
                            <tbody>
                                <Link as="tr" v-for="ticket in tickets.data" :key="ticket.id" :href="route('tickets.show', ticket.id)" class="border-b hover:bg-gray-100 cursor-pointer">
                                    <td class="p-4">{{ ticket.id }}</td>
                                    <td class="p-4">{{ ticket.title }}</td>
                                    <td class="p-4">{{ ticket.team.name }}</td>
                                    <td class="p-4">{{ ticket.user.name }}</td>
                                    <td class="p-4"><StatusBadge :status="ticket.status"/></td>
                                    <td class="p-4">{{ new Date(ticket.created_at).toLocaleString() }}</td>
                                </Link>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </AppLayout>
</template>

// PHP/phase4/deal-analyser/resources/js/Pages/Dashboard.jsx
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, usePage } from '@inertiajs/react';

export default function Dashboard() {
    const user = usePage().props.auth.user;
    return (
        <AuthenticatedLayout
            header={
                <h2 className="text-xl font-semibold leading-tight text-gray-800">
                    Dashboard
                </h2>
            }
        >
            <Head title="Dashboard" />

            <div className="py-12">
                <div className="mx-auto max-w-7xl sm:px-6 lg:px-8">
                    <div className="overflow-hidden bg-white shadow-sm sm:rounded-lg">
                        <div className="p-6 text-gray-900">
                            <div className="mb-4">You're logged in!</div>

                            {user.companyProfile ? (
                                <Link href={route('company.show', user.companyProfile.id)}>
                                    <button className="inline-flex items-center rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-700">
                                        View Company
                                    </button>
                                </Link>
                            ) : (
                                <Link href={route('company.create')}>
                                    <button className="inline-flex items-center rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-700">
                                        Create Company Profile
                                    </button>
                                </Link>
                            )}
                        </div>
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}
